In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import numpy as np
import data_generator
from args import read_args


In [3]:
import pandas as pd

In [4]:
args = read_args()
args

Namespace(A_n=28646, P_n=21044, V_n=18, batch_s=300, checkpoint='', cuda=0, data_path='../data/custom_data_simple/', embed_d=26, in_f_d=128, lr=0.001, mini_batch_s=100, model_path='../model_save/', random_seed=10, save_model_freq=2, train_iter_n=50, train_test_label=0, walk_L=30, walk_n=10, window=5)

In [5]:
input_data = data_generator.input_data(args=args)

# import json
# with open('../data/custom_data/node_mapping.json') as fin:
#     nodem = json.loads(fin.read())

# tnodem = {v:k for k,v in nodem.items()} 

# tnodem['a2']

# # nodem['2']

# for i in range(len(input_data.a_neigh_list_train)):
#     print(f'{i}: {input_data.a_neigh_list_train[i][6]}')

# import torch

# x = torch.randn(1, 3)
# x

# x.expand(32,-1)

Reading relation files a_a_list.txt
Reading relation files a_b_list.txt
Reading relation files a_c_list.txt
	Processed 4999 lines
Reading relation files a_d_list.txt
	Processed 4999 lines
Reading relation files a_e_list.txt
	Processed 4999 lines
Reading relation files a_f_list.txt
Reading relation files a_g_list.txt
	Processed 4999 lines
Reading relation files a_h_list.txt
Reading relation files b_a_list.txt
Reading relation files b_b_list.txt
Reading relation files b_c_list.txt
	Processed 4999 lines
	Processed 9999 lines
	Processed 14999 lines
	Processed 19999 lines
	Processed 24999 lines
Reading relation files b_d_list.txt
	Processed 4999 lines
	Processed 9999 lines
	Processed 14999 lines
Reading relation files b_e_list.txt
	Processed 4999 lines
	Processed 9999 lines
Reading relation files b_h_list.txt
Reading Node Edge Embedding file ../data/custom_data_simple/incoming_edge_embedding.csv
Creating Neighbour Edge Embeddings


In [6]:
# node_edge_embeddings = input_data.node_edge_embeddings

In [7]:
# node_edge_embeddings.shape
# n_nodes = 5044482

In [8]:
# graph_incoming_node_embedding = {}
# incoming_node_embedding_size = node_edge_embeddings.shape[1] - 2

# for row in node_edge_embeddings:
#     gid = int(row[0])
#     dst_id = int(row[1])
    
#     if gid not in graph_incoming_node_embedding.keys():
#         graph_incoming_node_embedding[gid] = np.zeros((n_dst_node, incoming_node_embedding_size))

#     graph_incoming_node_embedding[gid][dst_id] += row[2:]
# graph_incoming_node_embedding

In [9]:
# input_data.tmp['a_a']

In [10]:
# input_data.a_d_edge_embed

In [11]:
# input_data.incoming_edge_embeddings[0]

In [12]:
input_data.a_a_edge_embed[[0,2]]

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 3., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 2., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0.,

In [13]:
input_data.a_a_edge_embed[[0,2]].shape

(2, 12, 26)

In [14]:
input_data.a_a_edge_embed[[0,2]].reshape(2, 12*26)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 3., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 2.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [15]:
input_data.a_a_edge_embed[[0,2]].reshape(2, 1, 12*26).T.shape

(312, 1, 2)

In [16]:
input_data.a_a_edge_embed[[0,2]].reshape(2, 12*26).T

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [2., 2.],
       [3., 3.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.

In [17]:
import tools
import os
import torch
import torch.optim as optim

In [18]:
feature_list = [
            input_data.a_a_edge_embed,
            input_data.a_b_edge_embed,
            input_data.a_c_edge_embed,
            input_data.a_d_edge_embed,
            input_data.a_e_edge_embed,
            input_data.a_f_edge_embed,
            input_data.a_g_edge_embed,
            input_data.a_h_edge_embed,
            input_data.b_a_edge_embed,
            input_data.b_b_edge_embed,
            input_data.b_c_edge_embed,
            input_data.b_d_edge_embed,
            input_data.b_e_edge_embed,
            input_data.b_h_edge_embed
        ]

In [19]:
for i, fl in enumerate(feature_list):
            feature_list[i] = torch.from_numpy(np.array(feature_list[i])).float()

In [20]:
feature_list[0][0].size()

torch.Size([12, 26])

In [21]:
graph_train_id_list = input_data.train_graph_id_list

In [22]:
graph_train_id_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [23]:
model = tools.HetAgg(args, feature_list, graph_train_id_list)

In [24]:
model

HetAgg(
  (fc_a_a_agg): Linear(in_features=312, out_features=26, bias=True)
  (fc_a_b_agg): Linear(in_features=312, out_features=26, bias=True)
  (fc_a_c_agg): Linear(in_features=312, out_features=26, bias=True)
  (fc_a_d_agg): Linear(in_features=312, out_features=26, bias=True)
  (fc_a_e_agg): Linear(in_features=312, out_features=26, bias=True)
  (fc_a_f_agg): Linear(in_features=312, out_features=26, bias=True)
  (fc_a_g_agg): Linear(in_features=312, out_features=26, bias=True)
  (fc_a_h_agg): Linear(in_features=312, out_features=26, bias=True)
  (fc_b_a_agg): Linear(in_features=312, out_features=26, bias=True)
  (fc_b_b_agg): Linear(in_features=312, out_features=26, bias=True)
  (fc_b_c_agg): Linear(in_features=312, out_features=26, bias=True)
  (fc_b_d_agg): Linear(in_features=312, out_features=26, bias=True)
  (fc_b_e_agg): Linear(in_features=312, out_features=26, bias=True)
  (fc_b_h_agg): Linear(in_features=312, out_features=26, bias=True)
  (fc_het_neigh_agg): Linear(in_features

In [25]:
parameters = filter(lambda p: p.requires_grad, model.parameters())
optim = optim.Adam(parameters, lr=args.lr, weight_decay=0)
model.init_weights()

In [44]:
model.train()
model([0,1])

tensor([[-10.4094,  -6.5065, -12.1058, -13.2508,  -8.0205,  -5.5038,  -8.2451,
         -12.8506, -15.2601,  -4.8469,  -8.9490,  -4.0014,  -7.8161,  -7.1718,
          -8.7100,  -5.5961,  -2.0043, -11.7535, -12.0572,  -9.2990, -15.6931,
          -8.5654,  -9.1663, -20.2892, -21.0299, -19.5732],
        [-12.5751,  -6.8610,  -6.4315,  -8.2420,  -6.1343,  -7.4367,  -7.2967,
          -8.4533,  -8.1905,  -4.3780,  -8.2866,  -4.5851,  -5.5488,  -5.6877,
          -5.4663,  -6.1787,  -3.3881,  -9.3512,  -8.0886,  -7.5406, -13.0114,
          -8.7566,  -8.1452, -15.0398, -15.9120, -13.6070]],
       grad_fn=<LeakyReluBackward0>)

In [27]:
model.edge_content_agg([0,1], 'a_b')

tensor([[ 4.5960e+00, -4.9668e-02,  1.9191e+00,  1.6949e+00,  3.1416e-01,
          2.2472e+00, -6.6078e-02,  1.2835e+00, -1.9116e-02, -2.2845e-04,
         -3.4482e-03, -2.1231e-02, -3.9098e-02, -6.4082e-02,  9.6993e-01,
          3.2110e+00,  6.6395e-01,  1.2734e+00,  4.2702e+00,  5.4182e+00,
         -6.5543e-03, -4.1712e-02, -6.4573e-02, -2.1810e-03, -2.3831e-02,
          7.5825e+00],
        [ 5.1083e+00, -5.1790e-02,  2.0369e+00,  1.8667e+00, -4.9483e-04,
          2.4112e+00, -6.6096e-02,  1.4960e+00, -2.5074e-02,  2.4765e-01,
         -3.6351e-03, -2.3506e-02, -4.2307e-02, -6.9324e-02,  7.1641e-01,
          3.3172e+00,  6.2097e-01,  1.1204e+00,  4.6376e+00,  5.7226e+00,
         -5.1419e-03, -4.6511e-02, -6.7751e-02, -1.4799e-03, -2.6213e-02,
          8.0953e+00]], grad_fn=<ViewBackward0>)

In [29]:
def svdd_batch_loss(embed_batch): #nu: {0.1, 0.01}
    _batch_out = embed_batch
    _batch_out_resahpe = _batch_out.view(_batch_out.size()[0] * _batch_out.size()[1], embed_d)
    
    hypersphere_center = torch.mean(_batch_out_resahpe, 0)
    
    dist = torch.square(_batch_out_resahpe - hypersphere_center)
    
    return torch.mean(torch.sum(dist, 1))

# svdd_batch_loss(_out, batch_n)

In [31]:
model.train()
batch_s = args.batch_s
mini_batch_s = args.mini_batch_s
embed_d = args.embed_d

for iter_i in range(args.train_iter_n):
    print('iteration ' + str(iter_i) + ' ...')
    gid_list = np.array(range(600))
    batch_list = gid_list.reshape(int(600 / batch_s), batch_s)

    
    for batch_n, k in enumerate(batch_list):
        _out = torch.zeros(int(len(k) / mini_batch_s), mini_batch_s, embed_d)
        mini_batch_list = k.reshape(int(len(k) / mini_batch_s), mini_batch_s)
        for mini_n, mini_k in enumerate(mini_batch_list):
            _out_temp = model(mini_k)
            _out[mini_n] = _out_temp
        
        batch_loss = tools.svdd_batch_loss(_out)
        print(f'Batch Loss: {batch_loss}')
        optim.zero_grad()
        batch_loss.backward(retain_graph=True)
        optim.step()

iteration 0 ...
Batch Loss: 998769.1875
Batch Loss: 19455156.0
iteration 1 ...
Batch Loss: 656990.375
Batch Loss: 14246745.0
iteration 2 ...
Batch Loss: 419677.46875
Batch Loss: 10036445.0
iteration 3 ...
Batch Loss: 257699.046875
Batch Loss: 6800866.0
iteration 4 ...
Batch Loss: 151272.515625
Batch Loss: 4402917.0
iteration 5 ...
Batch Loss: 83769.6953125
Batch Loss: 2691663.0
iteration 6 ...
Batch Loss: 44503.828125
Batch Loss: 1494286.125
iteration 7 ...
Batch Loss: 22803.3125
Batch Loss: 735565.875
iteration 8 ...
Batch Loss: 10926.998046875
Batch Loss: 327469.9375
iteration 9 ...
Batch Loss: 4741.4248046875
Batch Loss: 147639.328125
iteration 10 ...
Batch Loss: 2171.076904296875
Batch Loss: 74407.3125
iteration 11 ...
Batch Loss: 1261.9591064453125
Batch Loss: 43297.19921875
iteration 12 ...
Batch Loss: 940.5889282226562
Batch Loss: 26772.544921875
iteration 13 ...
Batch Loss: 806.6353759765625
Batch Loss: 16400.189453125
iteration 14 ...
Batch Loss: 738.5416259765625
Batch Loss: 

In [41]:
batch_loss.tolist()

3400.495849609375

In [113]:
_out.size()

torch.Size([2, 3, 100, 26])

In [80]:
hypersphere_center = torch.mean(_out[batch_n].view(len(mini_batch_list) * mini_batch_s, embed_d), 0)
hypersphere_center

tensor([657.5353, 863.0911, 615.0443,   7.6595,  11.6553,  17.7259,  -7.7687,
        166.3391,  23.2053, 648.8605, 561.4694, 185.6070, 185.3958, 142.6107,
         -6.4988,  -5.6927, 240.8286, 101.9214, 343.2222,  25.8779, 198.3611,
         34.5414, 134.2992,  29.5433, 154.0036, 547.3102],
       grad_fn=<MeanBackward1>)

In [86]:
_out[batch_n].view(len(mini_batch_list) * mini_batch_s, embed_d) - hypersphere_center

tensor([[ 461.9786,  459.6783, -233.7465,  ...,  -33.1201, -159.7627,
          367.8847],
        [ 295.4781,  132.3753, -248.0656,  ...,  -32.7902, -155.9181,
          104.9939],
        [ 816.1484, 1347.2153,  857.7902,  ..., 1451.0356,  265.1805,
          645.9609],
        ...,
        [ 169.4581, -119.2835,  154.2783,  ...,  447.9461, -155.6930,
         -113.7345],
        [-100.5992, -754.9912,  -57.0236,  ...,  -40.5429, -158.7739,
           61.5334],
        [-283.9245,  122.8851,  116.9337,  ...,  -30.9534,  300.8385,
          557.7177]], grad_fn=<SubBackward0>)

In [101]:
# torch.mean(torch.sum(torch.sqrt(torch.square(_out[batch_n].view(len(mini_batch_list) * mini_batch_s, embed_d) - hypersphere_center)), dim=1))

tensor(4155.9966, grad_fn=<MeanBackward0>)

In [105]:
torch.mean(torch.sum(torch.square(_out[batch_n].view(len(mini_batch_list) * mini_batch_s, embed_d) - hypersphere_center), 1))

tensor(1942913.5000, grad_fn=<MeanBackward0>)

In [39]:
a = np.array(range(600))
np.random.shuffle(a)
np.mean(a)

299.5

In [192]:
all_gid_list = np.array(range(600))
benign_gid_list = all_gid_list[(all_gid_list < 300) | (all_gid_list > 399)]
attack_gid_list = np.array(range(300, 400))

# Train/Eval/Test = 0.6/0.2/0.2
train_benign_gid_list = np.random.choice(benign_gid_list, 360, replace=False)
left_benign_gid_list = benign_gid_list[np.in1d(
    benign_gid_list, train_benign_gid_list, invert=True)]

eval_benign_gid_list = np.random.choice(left_benign_gid_list, 70, replace=False)
test_benign_gid_list = left_benign_gid_list[np.in1d(
    left_benign_gid_list, eval_benign_gid_list, invert=True)]

train_attack_gid_list = np.random.choice(attack_gid_list, 60, replace=False)
left_attack_gid_list = attack_gid_list[np.in1d(
    attack_gid_list, train_attack_gid_list, invert=True)]
eval_attack_gid_list = np.random.choice(left_attack_gid_list, 20, replace=False)
test_attack_gid_list = left_attack_gid_list[np.in1d(
    left_attack_gid_list, eval_attack_gid_list, invert=True)]

train_gid_list = np.concatenate([train_benign_gid_list, train_attack_gid_list], axis=0) 
eval_gid_list = np.concatenate([eval_benign_gid_list, eval_attack_gid_list], axis=0)
test_gid_list = np.concatenate([test_benign_gid_list, test_attack_gid_list], axis=0)

np.random.shuffle(train_gid_list)
np.random.shuffle(eval_gid_list)
np.random.shuffle(test_gid_list)
np.random.shuffle(benign_gid_list)

In [193]:
train_gid_list

array([395, 529, 552, 542, 462, 534,  40,  34, 179, 247, 480,  89,  45,
       157, 114, 283, 550,  69, 402, 543, 476,  78,  26, 585, 199, 285,
       267,  98, 341,  99, 230, 223, 404, 459,  42,  79, 464,  82, 165,
       405, 184,  83, 259,   0, 557, 590, 394, 372, 272, 121, 486, 347,
       517, 444, 554, 428, 384, 222, 271,  46, 280,  24, 148, 200, 207,
        28, 562, 407, 409, 185,  54, 235,  13, 507, 385, 566, 158, 526,
       286, 248, 256, 252, 155, 153, 110, 437, 133, 328, 494, 460, 545,
       128, 573, 275, 596, 126,  65, 522, 589, 523, 423, 571, 583, 258,
       310, 152, 196, 365, 598, 216, 375, 575, 503, 338, 490, 530, 445,
       449, 333, 564, 304,  30, 364,  75, 474, 454, 380, 177, 466, 357,
       171, 173, 297, 498, 332, 197, 346, 563, 371,  38,  80, 447, 298,
       130, 142,  22, 509, 262, 349,  70, 591, 181, 147, 548, 439, 212,
       456, 481,  81, 389, 241, 254, 546, 540, 138,  64, 426, 484,   8,
       443, 170, 136,  14, 452, 166,  55, 475, 293, 581, 537, 59

In [194]:
eval_gid_list

array([236, 520, 224, 599, 440,  74,   1, 551, 379, 492, 189, 105, 487,
       544,  27, 411, 253, 306, 238, 307,  66, 348, 414, 410, 512, 438,
       560, 425, 549, 229,  72, 597, 532, 483, 141, 291,  18, 458, 227,
       469,  57, 390,  43, 352,   4, 326, 322, 288, 168, 336, 453, 577,
       331, 167, 102, 569, 329,  33, 108,  12,  91, 135, 112, 361,  59,
       393, 125, 574, 301,  44, 505, 508, 287, 209,  60, 159, 101, 362,
       461, 172,  76, 360,  62, 388, 218,  71, 314, 213, 324, 344])

In [195]:
test_gid_list

array([335,  35,  86, 149, 150, 140, 104, 282, 107, 539, 237, 163, 588,
       592, 234, 342, 232, 368, 219, 381, 315, 273, 413, 594, 327, 321,
       399,  97,  87, 162, 243, 370, 325, 541, 432, 134, 457, 477, 391,
       595,  51, 516, 513, 556, 164,  58,  15, 363,  67, 408, 531, 491,
       340, 468, 473, 514, 281, 127, 260, 292, 174, 356, 430, 396, 351,
        95, 369, 195,  56, 139,  96, 451, 377, 433, 193,  23, 182, 289,
       220, 203, 518, 221,  73, 587,   5, 586, 318, 188, 355, 567])

In [190]:
np.where((eval_gid_list >= 300) & (eval_gid_list < 400), 1, 0)

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [183]:
pred_X = model(eval_gid_list)
true_y = np.where((eval_gid_list >= 300) & (eval_gid_list < 400), 1, 0)

In [189]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(np.array(pred_X.tolist()), true_y)

In [188]:
clf.predict

array([[ -8.07654476,  -3.67806578,  -3.97940493, ...,  -5.61856508,
         -6.63739014,  -3.286201  ],
       [-25.30461121, -17.8821907 , -19.46343231, ..., -28.46804428,
        -23.69834137, -15.92532158],
       [ -4.52741814,  -4.9840641 ,  -4.52318239, ...,  -5.44792175,
         -7.24286461,  -6.37920046],
       ...,
       [-26.39011574, -21.42318153, -20.97297478, ..., -29.66191101,
        -19.13190269, -20.55114174],
       [ -4.7614584 ,  -4.15464735,  -2.90741062, ...,  -5.77147436,
         -6.88473701,  -5.26079416],
       [-29.96796799, -19.19325066, -22.16016579, ..., -27.75070953,
        -31.17169762, -20.11503029]])